apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: sles15sp2-dv
  name: sles15sp2-dv
spec:
  dataVolumeTemplates:
    - metadata:
        name: sles15sp2-dv
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
        source:
          http:
            url: "http://download.suse.de/ibs/Devel:/JeOS:/SLE-15-SP2/images/SLES15-SP2-JeOS.x86_64-OpenStack-Cloud.qcow2"
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: sles15sp2-dv
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - name: sles15sp2-dv
            disk:
              bus: virtio
          - name: cloudinit
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
            ports:
              - port: 22
        resources:
          requests:
            memory: 4Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: sles15sp2-dv
          dataVolume:
            name: sles15sp2-dv
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #cloud-config
              #hostname: test
              password: password
              chpasswd: { expire: False }
              ssh_pwauth: false
              disable_root: false
              ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPzn3riz+xnzuuEEsc8o8OGAZqw66b3A3U4ZnHU8DvLp1ysQN5fgxClU4sYmsz3+1yaR5F18NB6JWAANx5V5VtENRwuK2QZtXZX67Jw5NVm+u3fTOhP5m+2WYY+lfMW82DoY+OQ1566ruvFQyph1OqJeJ7A46WctL3YiogjT14DpZCIAYagSQHjVfnWZqtdkXmQatZdjZ7otx7OEP2lUK/SF9Dl2LZma9yuC7M1IpwHHRLK9pzGB3U0i00t9dnA8PlE1DlhmsF7J9M8PCBKfW9+0CymdNJDaC1f2ePHWlwoJ3qNL1eh0FmdmiikILkKY0sXPRnD4bDVX0p4m/b5ZHH chang@linux-hzdc
              #users:
              #  - name: test
              #    home: /home/test
              #    password: password
              #    chpasswd: { expire: False }
              #    ssh_pwauth: false
              #    disable_root: false
              #    sudo: ALL=(ALL) NOPASSWD:ALL
              #    ssh_authorized_keys:
              #    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPzn3riz+xnzuuEEsc8o8OGAZqw66b3A3U4ZnHU8DvLp1ysQN5fgxClU4sYmsz3+1yaR5F18NB6JWAANx5V5VtENRwuK2QZtXZX67Jw5NVm+u3fTOhP5m+2WYY+lfMW82DoY+OQ1566ruvFQyph1OqJeJ7A46WctL3YiogjT14DpZCIAYagSQHjVfnWZqtdkXmQatZdjZ7otx7OEP2lUK/SF9Dl2LZma9yuC7M1IpwHHRLK9pzGB3U0i00t9dnA8PlE1DlhmsF7J9M8PCBKfW9+0CymdNJDaC1f2ePHWlwoJ3qNL1eh0FmdmiikILkKY0sXPRnD4bDVX0p4m/b5ZHH chang@linux-hzdc
