apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: sles15sp2-vm-local
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: sles
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: local-sles-image
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
          interfaces:
          - name: default
            masquerade: {}
            ports:
              - port: 22
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      networks:
        - name: default
          pod: {}
      volumes:
      - name: local-sles-image
        persistentVolumeClaim:
          claimName: sles15sp2-local
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            #hostname: vm1
            password: password
            chpasswd: { expire: False }
            ssh_pwauth: false
            disable_root: false
            ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPzn3riz+xnzuuEEsc8o8OGAZqw66b3A3U4ZnHU8DvLp1ysQN5fgxClU4sYmsz3+1yaR5F18NB6JWAANx5V5VtENRwuK2QZtXZX67Jw5NVm+u3fTOhP5m+2WYY+lfMW82DoY+OQ1566ruvFQyph1OqJeJ7A46WctL3YiogjT14DpZCIAYagSQHjVfnWZqtdkXmQatZdjZ7otx7OEP2lUK/SF9Dl2LZma9yuC7M1IpwHHRLK9pzGB3U0i00t9dnA8PlE1DlhmsF7J9M8PCBKfW9+0CymdNJDaC1f2ePHWlwoJ3qNL1eh0FmdmiikILkKY0sXPRnD4bDVX0p4m/b5ZHH chang@linux-hzdc
