apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: windows
  name: win2k12
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: windows
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - cdrom:
              bus: sata
            bootOrder: 2
            name: win-image
          - disk:
              bus: virtio
            bootOrder: 1
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          interfaces:
          - name: default
            masquerade: {}
            ports:
              - port: 22
        machine:
          type: q35
        resources:
          requests:
            memory: 4Gi
      networks:
        - name: default
          pod: {}
      volumes:
      - name: win-image
        persistentVolumeClaim:
          claimName: win2k12
      - name: harddrive
        persistentVolumeClaim:
          claimName: win-harddisk
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
